### ISSUE TITLE
[ToDo] Documentation on how to use Monocoque with Proton Games

### ISSUE THREAD

**Issue by spikerguy** [Spacefreak18/monocoque#5]
I am making an issue list which I will assign to myself so I can improve the documentation slowly.

- [ ] How to Start monocoque?
- [ ] How to keep it on ?
- [ ] How to make it work with wine games ?
- [ ] How to make it work with proton games ?

**Comment by qreeves** [comment]
How to get involved with development?
What social channels are available?
What are the goals of the project?
What is needed to be done? Bonus: label good first issue.

**Comment by Spacefreak18** [comment]
Hi qreeves

first and foremost, just start using it first. We all use the software in different ways, so much of my use cases will be on the sims and cars I like. You may like something different, and you may notice different shortcomings or bugs because of that.

The goal is to be a complete open sourced alternative to simhub. With Linux suppport first.

With that being said, everything I've been doing has been written with supporting Windows in mind, so if you want to work on Windows porting, that would be welcomed too!

If you can't find something to work on on monocoque, the dashboard side of it a project called [simmonitor](https://github.com/Spacefreak18/simmonitor). And that project is very early days. As is monocoque, honestly.

Yeah, the TODO section of the README is horribly out of date, development is moving quickly.

And if you're interested in all things SimRacing on Linux, come join us on [matrix](https://matrix.to/#/#simracing:matrix.org).

Users and developers hang out there. We have people working on drivers, applications, space sims, you name it.
